export const EMAIL_REG = "[^@]+@[^@]+\.[a-zA-Z]{2,6}";
export const SUCCESS_MSG = "Успех!!";
export const ERROR_MSG = "Что-то пошло не так! Попробуйте ещё раз";
export const ERROR_MSG_NOT_FOUND = "Ничего не найдено";
export const ERROR_MSG_KEY_WORD = "Нужно ввести ключевое слово";
export const API_URL = "https://api.nomoreparties.co/";
export const MAIN_API_URL = "https://api.alexpozdniak.nomoredomainsrocks.ru";
export const MOVIES_ROUT = "/movies";
export const MAIN_ROUT = "/";
export const SAVE_MOVIES_ROUT = "/saved-movies";
export const PROFILE_ROUT = "/profile";
export const SIGN_UP_ROUT = "/signup";
export const SIGN_IN_ROUT = "/signin";
export const USER_ROUT = "/users/me";
export const ERROR_ROUT = "*";
export const JWT_LOCAL_KEY = "jwt";
export const CHECKBOX_LOCAL_KEY = "checked";
export const QUERRY_LOCAL_KEY = "query";
export const PRACTICUM_LINK = "https://practicum.yandex.ru/";
export const AUTHOR_GITHUB_LINK = "https://github.com/AlexPozdniak";
export const YOUTUBE_TRAILER_LINK = "https://www.youtube.com/results?search_query=трейлер+";
export const FILTERED_SHORTS_LOCAL_KEY = "filteredShorts";
export const FILTERED_MOVIES_LOCAL_KEY = "filteredMovies";
export const FILTERED_SAVE_MOVIES_LOCAL_KEY = "filteredSaveMovies"
export const FILTERED_SAVE_SHORTS_LOCAL_KEY = "filteredSaveShorts"
export const WRONG_FORMAT_ERROR_MSG = "Некорректный формат";
export const TRAVEL_PROJECT_LINK = "https://github.com/AlexPozdniak/russian-travel";
export const SECOND_PROJECT_LINK = "https://github.com/AlexPozdniak/second-project";
export const REACT_PROJECT_LINK = "https://github.com/AlexPozdniak/react-mesto-api-full-gha";
